#!/usr/bin/env bash
# Onboarding script: from a freshly-cloned freeq repo on a boxd VM to
# a fully-serving preview platform.
#
# Idempotent — safe to re-run after edits or to rotate the webhook secret.
#
# What it does, in order:
#   1. apt-installs the `webhook` binary if missing
#   2. Writes /etc/freeq-preview.conf (OWNER, REPO_NAME, BRANCH, REPO_DIR)
#   3. Generates or reuses the HMAC webhook secret (/etc/freeq-webhook-secret)
#   4. Renders /etc/freeq-webhook.conf.json from the template
#   5. Installs + restarts the freeq-webhook systemd unit
#   6. Creates the `hooks.<vm>.boxd.sh` boxd proxy → :9090
#   7. Registers the two GitHub webhooks (push + issue_comment) on the repo
#
# What it deliberately does NOT do (freeq stack runs natively on the host):
#   - No docker compose orchestration
#   - No language-runtime bootstrap (cargo / npm install assumed done by the
#     operator on first boot — see README.md)
#
# Auth: the script reuses whatever gh credentials are already present
# (GH_TOKEN env var or a prior `gh auth login`). Only if there are none
# at all do we fall back to a one-shot GH_TOKEN_INIT env var. The classic
# `repo` scope covers webhook management; fine-grained PATs additionally
# need `Webhooks: read+write` + `Administration: read` + `Issues/PRs:
# read+write`.
#
# Env-var overrides (all optional; defaults are golden-VM-appropriate):
#   OWNER=<github-account>      default: derived from repo origin URL
#   REPO_NAME=<repo>            default: freeq
#   ORIGIN_URL=<git url>        default: derived from OWNER/REPO_NAME
#   REPO_DIR=<path>             default: /home/boxd/freeq
#   VM_PREFIX=<prefix>          default: freeq-pr
#   VM_PREFIX_ISSUE=<prefix>    default: freeq-issue
#   DEFAULT_BRANCH=<branch>     default: main
#   WEBHOOK_SECRET=<hex>        default: reuse /etc/freeq-webhook-secret or
#                                        generate a fresh one
#   GH_TOKEN_INIT=<github pat>  one-shot gh CLI auth (use a fine-grained PAT)
set -euo pipefail

OPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Sanity: ensure we're running from inside the freeq repo tree.
if [ ! -d "$OPT_DIR/scripts" ] || [ ! -f "$OPT_DIR/config/webhook.conf.json.template" ]; then
  echo "ERROR: expected $OPT_DIR/{scripts,config} — is this freeq's scripts/preview/?" >&2
  exit 1
fi

# 1. webhook binary (Go, ~5MB, in Ubuntu main).
if ! command -v webhook >/dev/null 2>&1; then
  echo "==> apt installing webhook"
  sudo apt-get update -qq
  sudo apt-get install -y -qq webhook
fi

# 2. Write /etc/freeq-preview.conf.
USER_OWNER=${OWNER:-}
USER_REPO_NAME=${REPO_NAME:-}
USER_ORIGIN_URL=${ORIGIN_URL:-}
USER_REPO_DIR=${REPO_DIR:-}
USER_VM_PREFIX=${VM_PREFIX:-}
USER_VM_PREFIX_ISSUE=${VM_PREFIX_ISSUE:-}
USER_DEFAULT_BRANCH=${DEFAULT_BRANCH:-}

EXISTING_OWNER=""
EXISTING_ORIGIN_URL=""
EXISTING_REPO_DIR=""
EXISTING_REPO_NAME=""
EXISTING_VM_PREFIX=""
EXISTING_VM_PREFIX_ISSUE=""
EXISTING_DEFAULT_BRANCH=""
if [ -f /etc/freeq-preview.conf ]; then
  # shellcheck disable=SC1091
  . /etc/freeq-preview.conf
  EXISTING_OWNER=${OWNER:-}
  EXISTING_ORIGIN_URL=${ORIGIN_URL:-}
  EXISTING_REPO_DIR=${REPO_DIR:-}
  EXISTING_REPO_NAME=${REPO_NAME:-}
  EXISTING_VM_PREFIX=${VM_PREFIX:-}
  EXISTING_VM_PREFIX_ISSUE=${VM_PREFIX_ISSUE:-}
  EXISTING_DEFAULT_BRANCH=${DEFAULT_BRANCH:-}
  unset OWNER ORIGIN_URL REPO_DIR REPO_NAME VM_PREFIX VM_PREFIX_ISSUE DEFAULT_BRANCH
fi

REPO_DIR=${USER_REPO_DIR:-${EXISTING_REPO_DIR:-/home/boxd/freeq}}
DERIVED_OWNER=""
if [ -z "$USER_OWNER" ] && [ -z "$EXISTING_OWNER" ] && [ -d "$REPO_DIR/.git" ]; then
  CURRENT_ORIGIN_URL=$(cd "$REPO_DIR" && git remote get-url origin 2>/dev/null || echo "")
  DERIVED_OWNER=$(echo "$CURRENT_ORIGIN_URL" \
    | sed -E -e 's#\.git$##' -e 's#^https?://github\.com/##' -e 's#^git@github\.com:##' \
    | cut -d/ -f1)
fi

OWNER=${USER_OWNER:-${EXISTING_OWNER:-${DERIVED_OWNER:-MichielMAnalytics}}}
REPO_NAME=${USER_REPO_NAME:-${EXISTING_REPO_NAME:-freeq}}
ORIGIN_URL=${USER_ORIGIN_URL:-${EXISTING_ORIGIN_URL:-https://github.com/$OWNER/$REPO_NAME.git}}
VM_PREFIX=${USER_VM_PREFIX:-${EXISTING_VM_PREFIX:-freeq-pr}}
VM_PREFIX_ISSUE=${USER_VM_PREFIX_ISSUE:-${EXISTING_VM_PREFIX_ISSUE:-freeq-issue}}
DEFAULT_BRANCH=${USER_DEFAULT_BRANCH:-${EXISTING_DEFAULT_BRANCH:-main}}

if { [ -n "$USER_OWNER" ] || [ -n "$DERIVED_OWNER" ]; } && [ -z "$USER_ORIGIN_URL" ]; then
  ORIGIN_URL="https://github.com/$OWNER/$REPO_NAME.git"
fi

echo "==> writing /etc/freeq-preview.conf  (OWNER=$OWNER, REPO=$REPO_NAME, BRANCH=$DEFAULT_BRANCH)"
sudo tee /etc/freeq-preview.conf >/dev/null <<EOF
# Generated by scripts/preview/enable-preview.sh
OWNER=$OWNER
REPO_NAME=$REPO_NAME
ORIGIN_URL=$ORIGIN_URL
REPO_DIR=$REPO_DIR
VM_PREFIX=$VM_PREFIX
VM_PREFIX_ISSUE=$VM_PREFIX_ISSUE
DEFAULT_BRANCH=$DEFAULT_BRANCH
FREEQ_PREVIEW_OPT_DIR=$OPT_DIR
EOF

# Repoint repo origin if needed (covers the case where the operator cloned
# from upstream chad/freeq but OWNER points at their fork).
if [ -d "$REPO_DIR/.git" ]; then
  CURRENT_ORIGIN=$(cd "$REPO_DIR" && git remote get-url origin 2>/dev/null || echo "")
  if [ "$CURRENT_ORIGIN" != "$ORIGIN_URL" ]; then
    echo "==> repointing $REPO_DIR origin: $CURRENT_ORIGIN → $ORIGIN_URL"
    ( cd "$REPO_DIR" && git remote set-url origin "$ORIGIN_URL" )
  fi
  ( cd "$REPO_DIR" && git fetch --prune --quiet origin || true )
fi

# 3. Webhook secret.
if [ -z "${WEBHOOK_SECRET:-}" ]; then
  if [ -f /etc/freeq-webhook-secret ]; then
    WEBHOOK_SECRET=$(sudo cat /etc/freeq-webhook-secret)
    echo "==> reusing existing /etc/freeq-webhook-secret"
  else
    WEBHOOK_SECRET=$(openssl rand -hex 32)
    echo "==> generated new webhook secret"
  fi
fi
echo "$WEBHOOK_SECRET" | sudo tee /etc/freeq-webhook-secret >/dev/null
sudo chown root:boxd /etc/freeq-webhook-secret
sudo chmod 640 /etc/freeq-webhook-secret

# 4. Render webhook config.
echo "==> writing /etc/freeq-webhook.conf.json"
sudo sed \
  -e "s|@WEBHOOK_SECRET@|$WEBHOOK_SECRET|g" \
  -e "s|@OPT_DIR@|$OPT_DIR|g" \
  -e "s|@DEFAULT_BRANCH@|$DEFAULT_BRANCH|g" \
  "$OPT_DIR/config/webhook.conf.json.template" \
  | sudo tee /etc/freeq-webhook.conf.json >/dev/null
sudo chown root:boxd /etc/freeq-webhook.conf.json
sudo chmod 640 /etc/freeq-webhook.conf.json

# Log files for the async handlers + the listener itself.
for log in freeq-webhook.log freeq-golden-sync.log freeq-preview.log; do
  sudo touch "/var/log/$log"
  sudo chown boxd:boxd "/var/log/$log"
done

# 5. systemd unit.
echo "==> installing systemd unit"
sudo cp "$OPT_DIR/systemd/freeq-webhook.service" /etc/systemd/system/freeq-webhook.service
sudo systemctl daemon-reload
sudo systemctl enable freeq-webhook.service
sudo systemctl restart freeq-webhook.service

echo "==> webhook listener status:"
systemctl status freeq-webhook.service --no-pager --lines=0 || true

# 6. boxd proxy for the hooks subdomain.
VM_NAME=$(boxd info --json 2>/dev/null | jq -r '.name // empty' 2>/dev/null)
VM_NAME=${VM_NAME:-${boxd_vm_name:-$(hostname -s)}}
HOOKS_HOST="hooks.${VM_NAME}.boxd.sh"

if boxd proxy list --json 2>/dev/null | jq -e '.[] | select(.name=="hooks")' >/dev/null; then
  echo "==> hooks proxy already present"
else
  echo "==> creating hooks proxy → :9090"
  boxd proxy new hooks --port 9090 2>&1 | sed 's/^/    /'
fi

# 7. GitHub webhook registration.
echo
echo "==> registering GitHub webhooks"

OWNER_REPO=$(echo "$ORIGIN_URL" \
  | sed -E -e 's#\.git$##' -e 's#^https?://github\.com/##' -e 's#^git@github\.com:##')
if ! [[ "$OWNER_REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
  echo "    ERROR: could not extract owner/repo from ORIGIN_URL='$ORIGIN_URL'"
  exit 1
fi

# gh CLI auth: prefer the existing session (works with GH_TOKEN env vars
# or a prior `gh auth login`). Only fall back to GH_TOKEN_INIT if there's
# no usable auth at all. If we end up with neither, fail with a short hint.
if gh auth status >/dev/null 2>&1; then
  GH_USER=$(gh api user --jq .login 2>/dev/null || echo "?")
  echo "==> gh CLI already authenticated as $GH_USER — using existing credentials"
elif [ -n "${GH_TOKEN_INIT:-}" ]; then
  echo "==> authenticating gh CLI from GH_TOKEN_INIT"
  ( unset GH_TOKEN GITHUB_TOKEN
    printf '%s\n' "$GH_TOKEN_INIT" \
      | gh auth login --with-token --hostname github.com )
else
  cat >&2 <<HELP

  ERROR: gh CLI has no usable credentials. Run \`gh auth login\` first
  (or set GH_TOKEN / GITHUB_TOKEN in the environment), then re-run.

HELP
  exit 1
fi

# Idempotent webhook registration: drop any existing hooks targeting our
# hooks host, then add fresh ones with the current secret.
if HOOKS_JSON=$(gh api "/repos/$OWNER_REPO/hooks" 2>/dev/null) \
   && [ "$(echo "$HOOKS_JSON" | jq -r 'type' 2>/dev/null)" = "array" ]; then
  EXISTING=$(echo "$HOOKS_JSON" \
    | jq -r --arg host "$HOOKS_HOST" '.[] | select(.config.url | contains($host)) | .id')
  for id in $EXISTING; do
    echo "    removing pre-existing webhook $id"
    gh api -X DELETE "/repos/$OWNER_REPO/hooks/$id" >/dev/null
  done
else
  echo "    WARNING: couldn't list webhooks for $OWNER_REPO — skipping cleanup."
fi

for spec in deploy:push preview:issue_comment; do
  HOOK_ID=${spec%%:*}
  HOOK_EVENT=${spec#*:}
  HOOK_URL="https://$HOOKS_HOST/hooks/$HOOK_ID"
  POST_ERR=$(mktemp)
  if gh api -X POST "/repos/$OWNER_REPO/hooks" --input - >/dev/null 2>"$POST_ERR" <<JSON
{
  "name": "web",
  "active": true,
  "events": ["$HOOK_EVENT"],
  "config": {
    "url": "$HOOK_URL",
    "content_type": "json",
    "secret": "$WEBHOOK_SECRET",
    "insecure_ssl": "0"
  }
}
JSON
  then
    echo "    registered $HOOK_URL ($HOOK_EVENT)"
  else
    echo "    ERROR: failed to register $HOOK_URL"
    sed 's/^/      /' "$POST_ERR"
  fi
  rm -f "$POST_ERR"
done

echo
echo "==> done."
echo "    listener:  https://$HOOKS_HOST"
echo "    repo:      https://github.com/$OWNER_REPO"
echo "    tracking:  origin/$DEFAULT_BRANCH"
echo
echo "    Comment /boxd-preview on a PR or issue to spin up a preview env."
